ingress: "https://arbeidsgiver.labs.nais.io/samtalestotte-podlet"
liveness: "https://arbeidsgiver.labs.nais.io/samtalestotte-podlet/internal/isAlive"
readiness: "https://arbeidsgiver.labs.nais.io/samtalestotte-podlet/internal/isReady"
