apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "samtalestotte-podlet"
  namespace: "arbeidsgiver"
  labels:
    "team": "arbeidsgiver"
    "created-by": "teamia"
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
