ingress: "https://arbeidsgiver.nav.no/samtalestotte-podlet"
liveness: "https://arbeidsgiver.nav.no/samtalestotte-podlet/internal/isAlive"
readiness: "https://arbeidsgiver.nav.no/samtalestotte-podlet/internal/isReady"
