name: "Build and deploy samtalestotte-podlet"

on: [push]

env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-node@v1"
    - name: Install dependencies
      run: |
          yarn install --frozen-lockfile
    - name: "run tests"
      run: "yarn test"
    - name: "Login to GitHub Docker Registry"
      uses: "docker/login-action@v1"
      with:
        "registry": "ghcr.io"
        "username": "${{ github.actor }}"
        "password": "${{ secrets.GITHUB_TOKEN }}"
    - name: Build application
      run: |
          yarn run build
    - name: "Build and push the Docker image"
      run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"
  "deployAppToDev":
    name: "Deploy app to dev"
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/sende-til-dev-sbs'
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to DEV-labs"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "labs-gcp"
        "RESOURCE": ".nais/labs-gcp.yaml"
  "deployAppToDev-SBS":
    name: "Deploy app to dev-sbs"
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/sende-til-dev-sbs'
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to DEV-sbs"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-sbs"
        "RESOURCE": ".nais/dev-sbs.yaml"
  "deployAppToProd":
    name: "Deploy app to prod"
    if: github.ref == 'refs/heads/main'
    needs: "deployAppToDev"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to PROD"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "prod-gcp"
        "RESOURCE": ".nais/prod-gcp.yaml"
  "deployAlertsToDev":
    name: "Deploy alerts to dev"
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy alerts to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "labs-gcp"
        "RESOURCE": ".nais/alerts-dev.yaml"
        "VARS": ".nais/dev.yaml"
  "deployAlertsToProd":
    name: "Deploy alerts to prod"
    if: github.ref == 'refs/heads/main'
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy alerts to PROD"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "prod-sbs"
        "RESOURCE": ".nais/alerts-prod.yaml"
        "VARS": ".nais/prod.yaml"
